services:
  - type: web
    name: rice-price-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.main
    envVars:
      - key: API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://your-app-name.vercel.app